import json, os, sys
from pathlib import Path
def fail(msg): print("PREFLIGHT FAIL:",msg); sys.exit(1)
mode = sys.argv[1] if len(sys.argv)>1 else fail("usage")
rid = os.environ["GITHUB_RUN_ID"]; sha = os.environ["GITHUB_SHA"]
def exists(p,label): x=Path(p); (not x.exists() or not x.is_file()) and fail(label+" missing")
def jdict(p,label):
    exists(p,label)
    try: d=json.loads(Path(p).read_text())
    except Exception as e: fail(label+" JSON")
    if not isinstance(d,dict): fail(label+" not dict")
    return d
def chk_manifest(p):
    d=jdict(p,"manifest"); sv=d.get("schema_version")
    if type(sv) is not int or sv!=1: fail("manifest sv!=1")
    if d.get("run_id")!=rid: fail("manifest run_id")
    if d.get("head_sha")!=sha: fail("manifest sha")
    if d.get("job")!=mode: fail("manifest job")
if mode=="atos-tests":
    chk_manifest("evidence_manifest.json");exists("pytest.log","plog");exists("no_secret_scan.log","sec");exists("freqtrade_data/backtest_results/walk_forward_report.json","wfr")
elif mode=="freqtrade":
    chk_manifest("evidence_manifest.json");exists("freqtrade_data/backtest_results/canonical_baseline_summary.json","cs");exists("freqtrade_data/backtest_results/canonical_baseline_la_lookahead_status.json","cla")
    r1=jdict("validation_reports/strategy_fix_round1.json","r1");sv=r1.get("selected_variants")
    if not isinstance(sv,list) or not sv: fail("sv empty")
    for v in sv:
        if not isinstance(v,dict): fail("v not dict")
        bv=v.get("variant",""); lv=v.get("lookahead_variant","")
        if not bv: fail("bv empty")
        if not lv: fail("lv empty")
        if lv!=bv+"_la": fail("lv contract")
        sf=v.get("lookahead_status_file",""); rp=Path(sf)
        if ".." in sf or not rp.resolve().is_relative_to(Path.cwd().resolve()): fail("traversal")
        la=jdict(sf,"la"); a_variant=la.get("variant","?"); a_fs=la.get("final_status","?")
        if a_variant!=lv: fail("la.variant: "+str(a_variant)+" != "+lv)
        if a_fs!=v.get("lookahead_final_status"): fail("fs mismatch")
        sv_la=la.get("schema_version")
        if type(sv_la) is not int or sv_la!=1: fail("la sv")
        ps=la.get("parser_status")
        if ps not in ("PASS","FAIL","ERROR"): fail("la ps")
        fs=la.get("final_status")
        if fs not in ("PASS","PASS_WITH_RC_ANOMALY","FAIL","ERROR"): fail("la fs")
        hb=la.get("has_bias")
        if hb is not None and type(hb) is not bool: fail("la hb")
        fm=la.get("fatal_markers_found")
        if not isinstance(fm,list): fail("la fm")
        for x in fm:
            if not isinstance(x,str): fail("la fm item")
        rc=la.get("freqtrade_returncode")
        if type(rc) is not int or isinstance(rc,bool): fail("la rc")
        enb=la.get("explicit_no_bias_evidence")
        if type(enb) is not bool: fail("la enb")
        if fs=="PASS" and (ps!="PASS" or rc!=0 or fm or hb is not False): fail("PASS contract")
        if fs=="PASS_WITH_RC_ANOMALY" and (ps!="PASS" or rc==0 or enb is not True or fm or hb is not False): fail("ANOMALY contract")
        ob=la.get("output_base","")
        if not isinstance(ob,str) or not ob: fail("la ob")
        if ob!=lv: fail("la ob!=")
        es=la.get("evidence_source",""); rs=la.get("reason","")
        if not isinstance(es,str) or not es: fail("la evidence_source")
        if not isinstance(rs,str): fail("la reason")
        el=la.get("evidence_log","")
        if not isinstance(el,str) or not el: fail("la el")
else: fail("bad mode")
print("PREFLIGHT "+mode+" PASS")
