"""Public API for the frozen C5A research implementation."""
from .c5a_contract import (
    ABLATION_ID,
    ANNUAL_4H_BARS,
    BOUNDARY,
    CANDIDATE_ID,
    COMPARATORS,
    COST_LABELS,
    DOWNLOAD_START,
    EXPECTED_CONFIG_CANONICAL_SHA256,
    SPOT_INSTRUMENTS,
    SPOT_TO_SWAP,
    STEP,
    SWAP_INSTRUMENTS,
    C5AError,
    C5AMarket,
    build_calibration,
    calibration_decision_times,
    canonical_sha256,
    expected_timestamps,
    prepare_market,
    validate_config,
    window_decision_times,
)
from .c5a_policy import one_way_distance, signal_snapshot, solve_post_cost
from .c5a_simulation import simulate_policy_half
from .c5a_metrics import (
    aggregate_comparator,
    aggregate_policy,
    decide,
    run_screen,
    simulate_comparator_half,
)

__all__ = [
    "ABLATION_ID",
    "ANNUAL_4H_BARS",
    "BOUNDARY",
    "CANDIDATE_ID",
    "COMPARATORS",
    "COST_LABELS",
    "DOWNLOAD_START",
    "EXPECTED_CONFIG_CANONICAL_SHA256",
    "SPOT_INSTRUMENTS",
    "SPOT_TO_SWAP",
    "STEP",
    "SWAP_INSTRUMENTS",
    "C5AError",
    "C5AMarket",
    "aggregate_comparator",
    "aggregate_policy",
    "build_calibration",
    "calibration_decision_times",
    "canonical_sha256",
    "decide",
    "expected_timestamps",
    "one_way_distance",
    "prepare_market",
    "run_screen",
    "signal_snapshot",
    "simulate_comparator_half",
    "simulate_policy_half",
    "solve_post_cost",
    "validate_config",
    "window_decision_times",
]
