"""Frozen C8A historical research contract.

No value in this module enables account access, Paper, Shadow, derivatives
execution, or Live.  Funding is accounting only and never enters the signal.
"""

from __future__ import annotations

INSTRUMENTS = ("BTC-USDT-SWAP", "ETH-USDT-SWAP")
POLICIES = ("candidate", "cash", "always_long_perpetual")
COST_RATES = {"1.0x": 0.0015, "1.5x": 0.00225, "2.0x": 0.0030}

SIGNAL_CLOSE_COUNT = 169
TARGET_ABS_WEIGHT = 0.25
MAXIMUM_GROSS_NOTIONAL = 0.50
MINIMUM_SLEEVE_BUFFER = 1.25
EXPECTED_DECISIONS_PER_WINDOW = 26
EXPECTED_TOTAL_DECISIONS = 130
EXPECTED_INSTRUMENT_DIRECTIONS = 260

MINIMUM_POSITIVE_WINDOWS = 4
MINIMUM_WORST_WINDOW_RETURN = -0.05
MINIMUM_ANNUALIZED_SHARPE = 1.0
MINIMUM_PSR = 0.95
MAXIMUM_WINDOW_DRAWDOWN = 0.15
MAXIMUM_ABS_BETA = 0.65
MAXIMUM_ANNUALIZED_TURNOVER = 26.0
MINIMUM_NONFLAT_DIRECTIONS = 250
MAXIMUM_INSTRUMENT_CONCENTRATION = 0.75
MAXIMUM_WINDOW_CONCENTRATION = 0.45
MAXIMUM_WEEK_CONCENTRATION = 0.20
MAXIMUM_TOP_THREE_WEEK_CONCENTRATION = 0.45
MINIMUM_COMPARATOR_SHARPE_ADVANTAGE = 0.10

HISTORICAL_DATA_STATUS = "HISTORICAL_DEVELOPMENT_ONLY"
LIVE_STATE = "LIVE_FORBIDDEN"
PAPER_STATE = "PAPER_CLOSED"
SHADOW_STATE = "SHADOW_CLOSED"
